config/routes.rb
Rails.application.routes.draw do
  #get 'rockets/index'
  devise_for :users
  root to: "pages#home"

  resources :rockets, only: %i[index show new create destroy] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: [:index, :show]

  get "/my_rockets", to: "rockets#my_rockets"


  get '/search', to: 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rocket
  belongs_to :user
  validates :start_date, presence: true, comparison: { greater_than_or_equal_to: Date.today }
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  # validates :price, presence: true
  # validates :status, presence: true, length: { minimum: 2 }

  def total_price
    # @rocket = Rocket.find(params[:rocket_id])
    # @booking = Booking.find(params[:booking_id])
    total_days = end_date - start_date + 1
    total_days * rocket.price_per_earthday
  end
end

app/models/concerns/rocket_concern.rb
module RocketConcern
    def booked_dates
      # renvoie un array d'array des dates de debut et de fin de tous les bookings de la rocket
      bookings.pluck(:start_date, :end_date)
    end

    def simple_format_booked_dates
      # renvoie un array d'array des dates de debut et de fin
      # de tous les bookings de la rocket mais sous la forme stringifiée : "1991-12-28"
      booked_dates.deep_map(&:to_s)
    end

    def booked_dates_json_objects
      simple_format_booked_dates.map do |dates_arr|
        {
        from: dates_arr.first,
        to: dates_arr.last
        }
      end
    end

    def flatpickr_booked_dates_object
      {
      dateFormat: "Y-m-d",
      disable: booked_dates_json_objects
      }
    end
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  include RocketConcern
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :destination, presence: true, inclusion: { in: %w(Mars Earth Saturn Pluton Venus Mercure Moon), message: "%{value} is not a valid planet. Please choose a planet between :  Mars, Earth, Saturn, Pluton, Venus, Mercure and Moon."}
  validates :description, presence: true, length: { minimum: 2 }
  # validates :rating, :inclusion => { :in => 0..5 }, :presence => { :message => " must be within 0-5" }
  validates :name, presence: true

  include AlgoliaSearch

  algoliasearch do
    attribute :name, :description, :destination, :price_per_earthday
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :rockets, dependent: :destroy
  has_one_attached :photo
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :rating, :inclusion => { :in => 0..5 }, :presence => { :message => " must be within 0-5" }
  validates :planet_race, inclusion: { in: %w(Martian Human Saturnian Plutonian Venusian Mercurian Moonian), message: "%{value} is not a valid race. Please choose a race between : Martian, Human, Saturnian, Plutonian, Venusian, Mercurian, Moonian."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :user_params

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :planet_race])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :planet_race])
  end

  # def user_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :photo)
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @booking_list_as_owner = []
    @booking_list_as_traveller = []
    @bookings.each do |booking|
      @booking_list_as_owner << booking if booking.rocket.user == current_user
      @booking_list_as_traveller << booking if booking.user == current_user
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @marker = [{
      lat: @booking.rocket.latitude,
      lng: @booking.rocket.longitude,
      info_window_html: render_to_string(partial: "rockets/info_window", locals: {rocket: @booking.rocket}),
      marker_html: render_to_string(partial: "rockets/marker")
    }]
  end

  def new
    @booking = Booking.new
  end

  def create
    @rocket = Rocket.find(params[:rocket_id])
    @booking = Booking.new(booking_params)
    @booking.rocket = @rocket
    @booking.user = current_user
    @booking.price = total_price(@booking, @rocket)
    @booking.status = "booked"
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def total_price(booking, rocket)
    total_days = booking.end_date - booking.start_date + 1
    return total_days * rocket.price_per_earthday
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_rocket, only: [:show, :edit, :update, :destroy]

  def index
    Rocket.algolia_reindex!
    @rockets = Rocket.all
    @rockets = @rockets.search(params[:query], filters: price_filter)
    @markers = @rockets.map do |rocket|
      next unless rocket.latitude.present? && rocket.longitude.present?
      {
        lat: rocket.latitude,
        lng: rocket.longitude,
        info_window_html: render_to_string(partial: "rockets/info_window", locals: { rocket: rocket }),
        marker_html: render_to_string(partial: "rockets/marker")
      }
    end
  end

  def new
    @rocket = Rocket.new
    @rocket.user = current_user
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.user = current_user
    if @rocket.save!
      redirect_to rockets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.new
    @marker = [{
      lat: @rocket.latitude,
      lng: @rocket.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {rocket: @rocket}),
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def my_rockets
    @rockets = Rocket.where(user: current_user)
    @markers = @rockets.map do |rocket|
      next unless rocket.latitude.present? && rocket.longitude.present?
      {
        lat: rocket.latitude,
        lng: rocket.longitude,
        info_window_html: render_to_string(partial: "rockets/info_window", locals: { rocket: rocket }),
        marker_html: render_to_string(partial: "rockets/marker")
      }
    end
    render "my_rockets"
  end

  def destroy
    @rocket.destroy
    puts "hello"
    redirect_to my_rockets_path, status: :see_other
  end

  private

  def set_rocket
    @rocket = Rocket.find(params[:id])
  end

  def rocket_params
    params.require(:rocket).permit(:name, :destination, :description, :price_per_earthday, :rating, :user, :photo) # Adding picture url ?
  end

  def price_filter
    filters = []
    filters << "price_per_earthday >= #{params[:min_price]}" if params[:min_price].present?
    filters << "price_per_earthday <= #{params[:max_price]}" if params[:max_price].present?
    filters.join(" AND ")
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = AlgoliaSearch.search(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div class="card-trip">
  <div class="rocket-card-image">
    <%= cl_image_tag booking.rocket.photo.key, height: 200, width: 200, crop: :fill %>
    <%= cl_image_tag booking.rocket.user.photo.key, height: 40, width: 40, radius:"max"%>
  </div>
  <div class="card-trip-infos">
    <div>
      <h2>Recap of your booking :</h2>
      <ul>
        <li>Rocket: <b><%= booking.rocket.name %></b></li>
        <li>Your trip begins: <b><%= booking.start_date %></b></li>
        <li>You will be back to eath at: <b><%= booking.end_date %></b></li>
        <li>You will be away: <b><%= booking.end_date - booking.start_date + 1 %> days</b></li>
        <li>Going to: <b><%= booking.rocket.destination %></b></li>
      </ul>
    </div>
    <div>
      <h2 class="card-trip-pricing">Total StarCoins : <b><%= booking.price %></b></h2>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<div class="container">
  <div class="column">
    <div class="row">
<%# on veut une carte au milieu de la page avec les infos saisies (start et end date) + le calcul du prix (prix de base de la fusée * end - start date) + le status (confirmed)%>
      <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
          <div>
            <h2>Recap of your booking</h2>
            <p>Rocket name</p>
          </div>
          <h2 class="card-trip-pricing">Total : 1000000€</h2>
          <h2><%= cl_image_tag booking.rocket.user.photo.key, height: 40, width: 40 %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <div>
        <h1>My Bookings as an Owner of Rockets</h1>
      </div>
      <div class="row">
        <% @booking_list_as_owner.each do |booking| %>
          <div class="col-md-4">
            <%= render booking %>
          <% end %>
          </div>
      </div>
      <div>
        <h1>My trips as a Traveller</h1>
      </div>
      <div class="row">
        <% @booking_list_as_traveller.each do |booking| %>
          <div class="col-md-4">
            <%= render booking %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="column">
    <div class="row">
      <%= simple_form_for [@rocket, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-show">
  <div class="rocket-show-card">
    <h1>You booked <%= @booking.rocket.name %> rocket. Thanks!!</h1>
    <%= render @booking %>
  </div>
  <div class="rocket-show-card">
  <h3>This rocket offers a unique experience :</h3>
    <p><%= @booking.rocket.description %></p>
  </div>

  <div style="width: 100%; height: 250px;"
    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthentication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <div class="banner cover mt-5 mb-10 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586031/pexels-photo-586031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div class="container text-center text-black">
    <h1><strong> Indulge yourself with a fantastic Rocket Experience ! </strong></h1>
    <p>Explore our Unique Rocket offering.</p>
    <a class="btn btn-warning btn-flat mt-5" href="./rockets">Display Rockets to Rent</a>
  </div>
</div> %>

<div class="banner cover vh-100 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586031/pexels-photo-586031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2); background-size: cover;">
  <div class="container text-center text-white">
    <h1 class="display-4"><strong> Indulge yourself with a fantastic Rocket Experience ! </strong></h1>
    <br>
    <p class="lead">Explore our Unique Rocket offering.</p>
    <a class="btn btn-warning btn-lg mt-5" href="./rockets">Display Rockets to Rent</a>
  </div>
</div>

<%# <div class="banner cover vh-100 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586031/pexels-photo-586031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2); background-size: cover;">
  <div class="container text-center text-white">
    <h1 class="display-4 text-center" style="font-size: 4rem; margin-top: 10%;"><strong> Indulge yourself with a fantastic Rocket Experience ! </strong></h1>
    <br>
    <p class="lead">Explore our Unique Rocket offering.</p>
    <a class="btn btn-warning btn-lg mt-5" href="./rockets">Display Rockets to Rent</a>
  </div>
</div> %>




<%# <div class="banner cover vh-100 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586031/pexels-photo-586031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2); background-size: cover;">
  <div class="container text-center text-white">
    <h1 class="display-4"><strong> Indulge yourself with a fantastic Rocket Experience ! </strong></h1>
     <br>
    <p class="lead">Explore our Unique Rocket offering.</p>
    <a class="btn btn-warning btn-flat mt-5" href="./rockets">Display Rockets to Rent</a>
  </div>
</div> %>


<%# <div class="container"> %>
  <%# <div class="cover mt-5 mb-4 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path "sldxao2y6i46arsesgtv", height: 300, crop: :fill %>
    <%# <div class="text-center text-black"> %>
      <%# <h1 class="m-4">Indulge yourself with a fantastic Rocket Experience !</h1> %>
      <%# <h2 class="m-3">Explore our Unique Rocket offering</h2> %>
      <%# <%= link_to "Display all our Rockets to rent", rockets_path, class:"btn btn-secondary btn-flat mt-5 mb-4"%>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

app/views/rockets/_form.html.erb
<%= simple_form_for(rocket) do |f| %>
  <%= f.input :name %>
  <%= f.input :destination %>
  <%= f.input :description %>
  <%= f.input :price_per_earthday %>
  <%= f.input :address,
              input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
              wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Rent Your Rocket", class: "btn btn-flat" %>
<% end %>

app/views/rockets/_info_window.html.erb
<h2><%= rocket.name %></h2>
<p><%= rocket.address %></p>

app/views/rockets/_marker.html.erb
<%= image_tag "logo.jpg", height: 30, width: 30, alt: "Logo" %>

app/views/rockets/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Best Rockets to Rent</h1>
    </div>
  </div>
  <%= form_with url: rockets_path, method: :get, class: "d-flex m-4" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Where to take off ?"
  %>

  <%= text_field_tag :min_price,
    params[:min_price],
    class: "form-control",
    placeholder: "Min price?"
  %>

  <%= text_field_tag :max_price,
    params[:max_price],
    class: "form-control",
    placeholder: "Max price?"
  %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for rockets going to<strong><%= @query %></strong>. We found <%= @rockets.count %> rockets out of our <%= Rocket.count %> on our website.</p>
      <% else %>
        <p>We found <%= @rockets.count %> rockets out of <%= Rocket.count %> on our website.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @rockets.each do |rocket| %>
      <div class="col-md-4">
        <div class="rocket-card">
          <div class="rocket-card-image">
            <% if rocket.photo.key %>
              <%= cl_image_tag(rocket.photo.key, width: 400, height: 180, crop: :fill) %>
            <% end %>
            <%= cl_image_tag(rocket.user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          </div>
          <div class="rocket-card-content">
            <div class="rocket-card-title">
              <h4><%= rocket.name %></h4>
              <div>
                Owner: <%= rocket.user.first_name%>
              </div>
            </div>
            <p>Destination: <%= rocket.destination %></p>
            <p><%= rocket.description %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-star"></i>
                <span><%= rocket.rating %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <span>Price: <%= rocket.price_per_earthday %> StarCoins</span>
              </div>
            </div>
            <div style="width: 100%; height: 250px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
          <div class="rocket-card-actions">
            <%= link_to "Book this rocket", rocket_path(rocket), class: "btn btn-flat", target: :_blank %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rockets/my_rockets.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Here are all the rockets you're renting</h1>
    </div>
  </div>

  <div class="row">
    <% @rockets.each do |rocket| %>
      <div class="col-md-4">
        <div class="rocket-card">
          <div class="rocket-card-image">
            <% if rocket.photo.key %>
              <%= cl_image_tag(rocket.photo.key, width: 400, height: 180, crop: :fill) %>
            <% end %>
            <%= cl_image_tag(rocket.user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          </div>
          <div class="rocket-card-content">
            <div class="rocket-card-title">
              <h4><%= rocket.name %></h4>
              <div>
                Owner: <%= rocket.user.first_name%>
              </div>
            </div>
            <p>Destination: <%= rocket.destination %></p>
            <p><%= rocket.description %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-star"></i>
                <span><%= rocket.rating %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <span>Price: <%= rocket.price_per_earthday %> StarCoins</span>
              </div>
            </div>
            <div style="width: 100%; height: 250px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
          <div class="rocket-card-actions">
            <%= link_to "Delete", rocket_path(rocket.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rockets/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="rocket-form">
        <h1>Describe the Rocket to rent</h1>
        <div class="mt-3">
          <%= render "form", rocket: @rocket %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rockets/show.html.erb
<div class="container margin-top pb-5">
  <div class="row">
    <div class="col-8">
      <div class="rocket-show-card">
        <%= cl_image_tag(@rocket.photo.key, width: 800, height: 500, crop: :fill) %>
        <h1><%= @rocket.name %></h1>
        <h3 class="rocket-show-destination">Going to : <%= @rocket.destination %></h3>
      </div>
      <div class="rocket-show-card">
        <h3>This rocket offers a unique experience :</h3>
        <h4><%= @rocket.description %></h4>
      </div>
      <div style="width: 100%; height: 250px;"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

    <div class="col-4">
      <div class="rocket-show-card">
        <h1>Book this rocket!</h1>

          <%= simple_form_for [@rocket, @booking], html: { data: { controller: 'flatpickr', flatpickr_dates_value: @rocket.flatpickr_booked_dates_object } } do |f| %>
            <div class="d-flex">
              <%= f.input :start_date, as: :string, label:false, input_html: { data: {flatpickr_target: 'startDateInput', }} %>

              <%= f.input :end_date, as: :string, label: false, input_html: { data: { flatpickr_target: 'endDateInput', }} %>
            </div>

            <%= f.submit 'Book now!', class: 'btn btn-primary' %>
          <% end %>

        <%# <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%" onclick="window.location.href='booking>
        </form> %>

      </div>
      <div class="rocket-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            Rating : <%= @rocket.rating %>
          </div>
          <div class="flex ms-3">
            <%= @rocket.price_per_earthday %> StarCoins / EarthDay
          </div>
        </div>
      </div>
      <div class="rocket-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <i class="fa-solid fa-rocket fa-lg"></i>
    <% end %>
      <h2 style="color: white;"><b>StarBnB</b></h2>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Display Rockets", rockets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Rent your Rocket", new_rocket_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
              <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My rockets", my_rockets_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>